language: rust
rust:
  - nightly-2017-03-15
sudo: required
os:
  - linux
  - osx
dist: trusty
addons:
  apt:
    packages:
      - xorg-dev
      - libmagic-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libmagic; fi
script:
  - cargo build --verbose --no-default-features --features "rustls"
  - cargo build --verbose --no-default-features --features "rustls file_type_checking"
  - cargo build --verbose --no-default-features --features "rustls clipboard_support"
  - cargo build --verbose --no-default-features --features "rustls file_type_checking clipboard_support"
  - cargo build --verbose --no-default-features --features "openssl"
  - cargo build --verbose --no-default-features --features "openssl file_type_checking"
  - cargo build --verbose --no-default-features --features "openssl clipboard_support"
  - cargo build --verbose --no-default-features --features "openssl file_type_checking clipboard_support"
notifications:
  email: false
