language: rust
rust:
  - stable
  - beta
  - nightly
sudo: required
os:
  - linux
  - osx
dist: trusty
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - xorg-dev
      - libmagic-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libmagic; fi
script:
  - cargo build --verbose
  - cargo build --verbose --no-default-features
  - cargo build --verbose --features file_type_checking
  # Currently no tests
  # - cargo test --verbose
notifications:
  email: false
