environment:
  matrix:
  - TARGET: i686-pc-windows-gnu
    MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.9.2/threads-win32/dwarf/i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z/download
    MINGW_ARCHIVE: i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z
    MINGW_DIR: mingw32
    BITS: 32
  - TARGET: x86_64-pc-windows-gnu
    MSYS_BITS: 64
    BITS: 64
  # only gnu for now because windows is 0/10
  # - TARGET: i686-pc-windows-msvc
    # BITS: 32
  # - TARGET: x86_64-pc-windows-msvc
    # BITS: 64

install:
  # Install rust, x86_64-pc-windows-msvc host
  # FIXME: switch back to win.rustup.rs
  - ps: Start-FileDownload "http://slproweb.com/download/Win${env:BITS}OpenSSL-1_0_2h.exe"
  - Win%BITS%OpenSSL-1_0_2h.exe /SILENT /VERYSILENT /SP- /DIR="C:\OpenSSL"
  - set OPENSSL_LIB_DIR=C:/OpenSSL
  - set OPENSSL_INCLUDE_DIR=C:/OpenSSL/include
  - curl -sSf -o rustup-init.exe https://dev-static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe
  - rustup-init.exe -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustup default nightly-2016-05-10-x86_64-pc-windows-msvc

  # Install the target we're compiling for
  - if NOT "%TARGET%" == "x86_64-pc-windows-msvc" rustup target add %TARGET%

  # Use the system msys if we can
  - if defined MSYS_BITS set PATH=C:\msys64\mingw%MSYS_BITS%\bin;C:\msys64\usr\bin;%PATH%

  # download a custom compiler otherwise
  - if defined MINGW_ARCHIVE appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
  - if defined MINGW_ARCHIVE 7z x -y "%MINGW_ARCHIVE%" > nul
  - if defined MINGW_ARCHIVE set PATH=%CD%\%MINGW_DIR%\bin;C:\msys64\usr\bin;%PATH%

  # let's see what we got
  - where gcc rustc cargo
  - rustc -vV
  - cargo -vV
  - set CARGO_TARGET_DIR=%CD%\target

build: false

test_script:
  - cargo build --verbose --target %TARGET%
  - cargo build --verbose --no-default-features --target %TARGET%
  # figure out how to libmagic on Windows first
  # - cargo build --verbose --features file_type_checking --target %TARGET%
