[package]
name = "bins"
version = "0.1.0"
authors = ["Kyle Clemens <jkc.clemens@gmail.com>"]

[dependencies]
config = "0.1.3"
argparse = "0.2.1"
hyper = "0.9"
rustc-serialize = "0.3.19"

[dependencies.url]
git = "https://github.com/servo/rust-url"
