[package]
name = "bins"
version = "1.2.0"
description = "A tool for pasting from the terminal."
authors = ["Kyle Clemens <me@kyleclemens.com>"]
repository = "https://github.com/jkcclemens/bins"
readme = "README.md"
license = "MPL-2.0"

build = "build.rs"

[features]
default = ["clipboard_support"]
clipboard_support = ["clipboard"]
file_type_checking = ["magic-sys", "libc"]

[dependencies]
toml = "0.1.30"
clap = "2.9.1"
hyper = "0.9.9"
rand = "0.3.14"
rustc-serialize = "0.3.19"
error-chain = "0.2.1"
linked-hash-map = "0.1.0"
lazy_static = "0.2.1"
cfg-if = "0.1.0"
url = "1.1.1"
magic-sys = { version = "0.2.0", optional = true }
libc = { version = "0.2.13", optional = true }
clipboard = { version = "0.1.2", optional = true }

[build-dependencies]
git2 = "0.4.3"
rustc_version = "0.1.7"

[profile.release]
lto = true
# panic = "abort"
