[package]
name = "bins"
version = "1.0.0"
description = "A tool for pasting from the terminal."
authors = ["Kyle Clemens <me@kyleclemens.com>"]
repository = "https://github.com/jkcclemens/bins"
readme = "README.md"
license = "MPL-2.0"

build = "build.rs"

[features]
default = ["clipboard_support"]
clipboard_support = ["clipboard"]

[dependencies]
toml = "0.1.30"
clap = "2.6.0"
hyper = "0.9.9"
rand = "0.3.14"
rustc-serialize = "0.3.19"
error-chain = "0.1.12"
linked-hash-map = "0.0.10"
lazy_static = "0.2.1"
cfg-if = "0.1.0"
url = "1.1.1"
clipboard = { version = "0.1.2", optional = true }

[build-dependencies]
git2 = "0.4.3"
rustc_version = "0.1.7"

[profile.release]
lto = true
